version: '3'
services:
  shoestop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shoestop
    ports:
     - '5000:5000'
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - '8080:8080'
    volumes:
      - /home/ubuntu/Hackathon-Application/shoestop/jenkins:/var/jenkins_home


